import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export interface Language {
  code: string;
  name: string;
  flag: string;
  nativeName: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸', nativeName: 'English' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
  { code: 'fr', name: 'French', flag: '🇫🇷', nativeName: 'Français' },
  { code: 'de', name: 'German', flag: '🇩🇪', nativeName: 'Deutsch' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺', nativeName: 'Русский' },
  { code: 'it', name: 'Italian', flag: '🇮🇹', nativeName: 'Italiano' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹', nativeName: 'Português' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳', nativeName: '中文' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵', nativeName: '日本語' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷', nativeName: '한국어' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦', nativeName: 'العربية' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी' },
  { code: 'he', name: 'Hebrew', flag: '🇮🇱', nativeName: 'עברית' },
  { code: 'sv', name: 'Swedish', flag: '🇸🇪', nativeName: 'Svenska' },
  { code: 'pl', name: 'Polish', flag: '🇵🇱', nativeName: 'Polski' }
];

// Translation keys and their values for different languages
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.messages': 'Messages',
    'nav.leads': 'Leads',
    'nav.profile': 'Profile',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.ok': 'OK',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Home Screen
    'home.welcome': 'Welcome back,',
    'home.newRequest': 'New Request',
    'home.getHelpNow': 'Get help now',
    'home.browseRequests': 'Browse Requests',
    'home.findNewJobs': 'Find new jobs',
    'home.availableRequests': 'Available Requests',
    'home.recentRequests': 'Recent Requests',
    'home.recentJobs': 'Recent Jobs',
    'home.noRequestsYet': 'No requests yet',
    'home.noJobsYet': 'No jobs yet',
    'home.createFirstRequest': 'Create your first request to get started',
    'home.browseAvailableRequests': 'Browse available requests to get started',
    'home.createRequest': 'Create Request',
    'home.tapToView': 'Tap to view details',
    'home.referFriend': 'Refer a Friend & Earn $10',
    'home.shareRigSnap': 'Share RigSnap and get rewarded when they join',
    
    // Profile Screen
    'profile.title': 'Profile',
    'profile.personalInformation': 'Personal Information',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.location': 'Location',
    'profile.memberSince': 'Member Since',
    'profile.truckerInformation': 'Trucker Information',
    'profile.truckType': 'Truck Type',
    'profile.licenseNumber': 'License Number',
    'profile.serviceProviderInformation': 'Service Provider Information',
    'profile.servicesOffered': 'Services Offered',
    'profile.serviceRadius': 'Service Radius',
    'profile.certifications': 'Certifications',
    'profile.paymentMethods': 'Payment Methods',
    'profile.settings': 'Settings',
    'profile.accountSettings': 'Account Settings',
    'profile.languageRegion': 'Language & Region',
    'profile.signOut': 'Sign Out',
    'profile.rating': 'rating',
    'profile.notProvided': 'Not provided',
    'profile.notSpecified': 'Not specified',
    'profile.miles': 'miles',
    'profile.editProfile': 'Edit Profile',
    'profile.saveChanges': 'Save Changes',
    'profile.cancel': 'Cancel',
    
    // Messages/Chat
    'chat.title': 'Messages',
    'chat.messages': 'Messages',
    'chat.noMessagesYet': 'No messages yet',
    'chat.messagesWillAppear': 'Messages will appear here when you start chatting with service providers',
    'chat.messagesWillAppearProvider': 'Messages will appear here when you accept service requests',
    'chat.active': 'Active',
    'chat.completed': 'Completed',
    'chat.typeMessage': 'Type a message...',
    'chat.trucker': 'Trucker',
    'chat.serviceProvider': 'Service Provider',
    
    // Leads
    'leads.title': 'Lead Tracking',
    'leads.leadTracking': 'Lead Tracking',
    'leads.monitorLeadFees': 'Monitor your lead fees and transactions',
    'leads.netSpent': 'Net Spent',
    'leads.totalLeads': 'Total Leads',
    'leads.refunded': 'Refunded',
    'leads.penalties': 'Penalties',
    'leads.pending': 'Pending',
    'leads.transactionHistory': 'Transaction History',
    'leads.noLeadFeesYet': 'No lead fees yet',
    'leads.leadFeesWillAppear': 'Lead fees will appear here when service providers accept your requests',
    'leads.leadFeesWillAppearProvider': 'Lead fees will appear here when you accept service requests',
    
    // Account Settings
    'settings.title': 'Account Settings',
    'settings.security': 'Security',
    'settings.changePassword': 'Change Password',
    'settings.updatePassword': 'Update your account password',
    'settings.languageRegion': 'Language & Region',
    'settings.language': 'Language',
    'settings.currentLanguage': 'Current',
    'settings.notifications': 'Notifications',
    'settings.pushNotifications': 'Push Notifications',
    'settings.emailNotifications': 'Email Notifications',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.requestUpdates': 'Request Updates',
    'settings.securityAlerts': 'Security Alerts',
    'settings.marketingEmails': 'Marketing Emails',
    'settings.appPreferences': 'App Preferences',
    'settings.darkMode': 'Dark Mode',
    'settings.support': 'Support',
    'settings.helpCenter': 'Help Center',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    
    // Service Types
    'service.towing': 'Towing Service',
    'service.repair': 'Road Service', 
    'service.mechanic': 'Mechanic Service',
    'service.tireRepair': 'Mobile Tire Repair',
    'service.truckWash': 'Mobile Truck Wash',
    'service.hoseRepair': 'Hose Repair',
    
    // Status
    'status.pending': 'Pending',
    'status.accepted': 'Accepted',
    'status.inProgress': 'In Progress',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    
    // Urgency
    'urgency.low': 'Low',
    'urgency.medium': 'Medium',
    'urgency.high': 'High',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.messages': 'Mensajes',
    'nav.leads': 'Clientes',
    'nav.profile': 'Perfil',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.ok': 'OK',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.submit': 'Enviar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    
    // Home Screen
    'home.welcome': 'Bienvenido de nuevo,',
    'home.newRequest': 'Nueva Solicitud',
    'home.getHelpNow': 'Obtener ayuda ahora',
    'home.browseRequests': 'Explorar Solicitudes',
    'home.findNewJobs': 'Encontrar nuevos trabajos',
    'home.availableRequests': 'Solicitudes Disponibles',
    'home.recentRequests': 'Solicitudes Recientes',
    'home.recentJobs': 'Trabajos Recientes',
    'home.noRequestsYet': 'Aún no hay solicitudes',
    'home.noJobsYet': 'Aún no hay trabajos',
    'home.createFirstRequest': 'Crea tu primera solicitud para comenzar',
    'home.browseAvailableRequests': 'Explora las solicitudes disponibles para comenzar',
    'home.createRequest': 'Crear Solicitud',
    'home.tapToView': 'Toca para ver detalles',
    'home.referFriend': 'Refiere un Amigo y Gana $10',
    'home.shareRigSnap': 'Comparte RigSnap y obtén recompensas cuando se unan',
    
    // Profile Screen
    'profile.title': 'Perfil',
    'profile.personalInformation': 'Información Personal',
    'profile.name': 'Nombre',
    'profile.email': 'Correo',
    'profile.phone': 'Teléfono',
    'profile.location': 'Ubicación',
    'profile.memberSince': 'Miembro Desde',
    'profile.truckerInformation': 'Información del Camionero',
    'profile.truckType': 'Tipo de Camión',
    'profile.licenseNumber': 'Número de Licencia',
    'profile.serviceProviderInformation': 'Información del Proveedor de Servicios',
    'profile.servicesOffered': 'Servicios Ofrecidos',
    'profile.serviceRadius': 'Radio de Servicio',
    'profile.certifications': 'Certificaciones',
    'profile.paymentMethods': 'Métodos de Pago',
    'profile.settings': 'Configuración',
    'profile.accountSettings': 'Configuración de Cuenta',
    'profile.languageRegion': 'Idioma y Región',
    'profile.signOut': 'Cerrar Sesión',
    'profile.rating': 'calificación',
    'profile.notProvided': 'No proporcionado',
    'profile.notSpecified': 'No especificado',
    'profile.miles': 'millas',
    'profile.editProfile': 'Editar Perfil',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.cancel': 'Cancelar',
    
    // Messages/Chat
    'chat.title': 'Mensajes',
    'chat.messages': 'Mensajes',
    'chat.noMessagesYet': 'Aún no hay mensajes',
    'chat.messagesWillAppear': 'Los mensajes aparecerán aquí cuando comiences a chatear con proveedores de servicios',
    'chat.messagesWillAppearProvider': 'Los mensajes aparecerán aquí cuando aceptes solicitudes de servicio',
    'chat.active': 'Activo',
    'chat.completed': 'Completado',
    'chat.typeMessage': 'Escribe un mensaje...',
    'chat.trucker': 'Camionero',
    'chat.serviceProvider': 'Proveedor de Servicios',
    
    // Leads
    'leads.title': 'Seguimiento de Clientes',
    'leads.leadTracking': 'Seguimiento de Clientes',
    'leads.monitorLeadFees': 'Monitorea tus tarifas de clientes y transacciones',
    'leads.netSpent': 'Gasto Neto',
    'leads.totalLeads': 'Total de Clientes',
    'leads.refunded': 'Reembolsado',
    'leads.penalties': 'Penalizaciones',
    'leads.pending': 'Pendiente',
    'leads.transactionHistory': 'Historial de Transacciones',
    'leads.noLeadFeesYet': 'Aún no hay tarifas de clientes',
    'leads.leadFeesWillAppear': 'Las tarifas de clientes aparecerán aquí cuando los proveedores de servicios acepten tus solicitudes',
    'leads.leadFeesWillAppearProvider': 'Las tarifas de clientes aparecerán aquí cuando aceptes solicitudes de servicio',
    
    // Account Settings
    'settings.title': 'Configuración de Cuenta',
    'settings.security': 'Seguridad',
    'settings.changePassword': 'Cambiar Contraseña',
    'settings.updatePassword': 'Actualiza la contraseña de tu cuenta',
    'settings.languageRegion': 'Idioma y Región',
    'settings.language': 'Idioma',
    'settings.currentLanguage': 'Actual',
    'settings.notifications': 'Notificaciones',
    'settings.pushNotifications': 'Notificaciones Push',
    'settings.emailNotifications': 'Notificaciones por Email',
    'settings.smsNotifications': 'Notificaciones SMS',
    'settings.requestUpdates': 'Actualizaciones de Solicitudes',
    'settings.securityAlerts': 'Alertas de Seguridad',
    'settings.marketingEmails': 'Emails de Marketing',
    'settings.appPreferences': 'Preferencias de la App',
    'settings.darkMode': 'Modo Oscuro',
    'settings.support': 'Soporte',
    'settings.helpCenter': 'Centro de Ayuda',
    'settings.privacyPolicy': 'Política de Privacidad',
    'settings.dangerZone': 'Zona de Peligro',
    'settings.deleteAccount': 'Eliminar Cuenta',
    
    // Service Types
    'service.towing': 'Servicio de Remolque',
    'service.repair': 'Servicio en Carretera',
    'service.mechanic': 'Servicio Mecánico',
    'service.tireRepair': 'Reparación Móvil de Llantas',
    'service.truckWash': 'Lavado Móvil de Camiones',
    'service.hoseRepair': 'Reparación de Mangueras',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.messages': 'Messages',
    'nav.leads': 'Prospects',
    'nav.profile': 'Profil',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.ok': 'OK',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.submit': 'Soumettre',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    
    // Home Screen
    'home.welcome': 'Bon retour,',
    'home.newRequest': 'Nouvelle Demande',
    'home.getHelpNow': 'Obtenir de l\'aide maintenant',
    'home.browseRequests': 'Parcourir les Demandes',
    'home.findNewJobs': 'Trouver de nouveaux emplois',
    'home.availableRequests': 'Demandes Disponibles',
    'home.recentRequests': 'Demandes Récentes',
    'home.recentJobs': 'Emplois Récents',
    'home.noRequestsYet': 'Aucune demande pour le moment',
    'home.noJobsYet': 'Aucun emploi pour le moment',
    'home.createFirstRequest': 'Créez votre première demande pour commencer',
    'home.browseAvailableRequests': 'Parcourez les demandes disponibles pour commencer',
    'home.createRequest': 'Créer une Demande',
    'home.tapToView': 'Appuyez pour voir les détails',
    'home.referFriend': 'Parrainez un Ami et Gagnez 10$',
    'home.shareRigSnap': 'Partagez RigSnap et soyez récompensé quand ils rejoignent',
    
    // Profile Screen
    'profile.title': 'Profil',
    'profile.personalInformation': 'Informations Personnelles',
    'profile.name': 'Nom',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.location': 'Localisation',
    'profile.memberSince': 'Membre Depuis',
    'profile.truckerInformation': 'Informations du Camionneur',
    'profile.truckType': 'Type de Camion',
    'profile.licenseNumber': 'Numéro de Licence',
    'profile.serviceProviderInformation': 'Informations du Fournisseur de Services',
    'profile.servicesOffered': 'Services Offerts',
    'profile.serviceRadius': 'Rayon de Service',
    'profile.certifications': 'Certifications',
    'profile.paymentMethods': 'Méthodes de Paiement',
    'profile.settings': 'Paramètres',
    'profile.accountSettings': 'Paramètres du Compte',
    'profile.languageRegion': 'Langue et Région',
    'profile.signOut': 'Se Déconnecter',
    'profile.rating': 'évaluation',
    'profile.notProvided': 'Non fourni',
    'profile.notSpecified': 'Non spécifié',
    'profile.miles': 'miles',
    'profile.editProfile': 'Modifier le Profil',
    'profile.saveChanges': 'Enregistrer les Modifications',
    'profile.cancel': 'Annuler',
    
    // Messages/Chat
    'chat.title': 'Messages',
    'chat.messages': 'Messages',
    'chat.noMessagesYet': 'Aucun message pour le moment',
    'chat.messagesWillAppear': 'Les messages apparaîtront ici quand vous commencerez à discuter avec les fournisseurs de services',
    'chat.messagesWillAppearProvider': 'Les messages apparaîtront ici quand vous accepterez des demandes de service',
    'chat.active': 'Actif',
    'chat.completed': 'Terminé',
    'chat.typeMessage': 'Tapez un message...',
    'chat.trucker': 'Camionneur',
    'chat.serviceProvider': 'Fournisseur de Services',
    
    // Leads
    'leads.title': 'Suivi des Prospects',
    'leads.leadTracking': 'Suivi des Prospects',
    'leads.monitorLeadFees': 'Surveillez vos frais de prospects et transactions',
    'leads.netSpent': 'Dépenses Nettes',
    'leads.totalLeads': 'Total des Prospects',
    'leads.refunded': 'Remboursé',
    'leads.penalties': 'Pénalités',
    'leads.pending': 'En Attente',
    'leads.transactionHistory': 'Historique des Transactions',
    'leads.noLeadFeesYet': 'Aucun frais de prospect pour le moment',
    'leads.leadFeesWillAppear': 'Les frais de prospects apparaîtront ici quand les fournisseurs de services accepteront vos demandes',
    'leads.leadFeesWillAppearProvider': 'Les frais de prospects apparaîtront ici quand vous accepterez des demandes de service',
    
    // Account Settings
    'settings.title': 'Paramètres du Compte',
    'settings.security': 'Sécurité',
    'settings.changePassword': 'Changer le Mot de Passe',
    'settings.updatePassword': 'Mettez à jour le mot de passe de votre compte',
    'settings.languageRegion': 'Langue et Région',
    'settings.language': 'Langue',
    'settings.currentLanguage': 'Actuel',
    'settings.notifications': 'Notifications',
    'settings.pushNotifications': 'Notifications Push',
    'settings.emailNotifications': 'Notifications Email',
    'settings.smsNotifications': 'Notifications SMS',
    'settings.requestUpdates': 'Mises à Jour des Demandes',
    'settings.securityAlerts': 'Alertes de Sécurité',
    'settings.marketingEmails': 'Emails Marketing',
    'settings.appPreferences': 'Préférences de l\'App',
    'settings.darkMode': 'Mode Sombre',
    'settings.support': 'Support',
    'settings.helpCenter': 'Centre d\'Aide',
    'settings.privacyPolicy': 'Politique de Confidentialité',
    'settings.dangerZone': 'Zone de Danger',
    'settings.deleteAccount': 'Supprimer le Compte',
    
    // Service Types
    'service.towing': 'Service de Remorquage',
    'service.repair': 'Service Routier',
    'service.mechanic': 'Service Mécanique',
    'service.tireRepair': 'Réparation Mobile de Pneus',
    'service.truckWash': 'Lavage Mobile de Camions',
    'service.hoseRepair': 'Réparation de Tuyaux',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.messages': 'Nachrichten',
    'nav.leads': 'Leads',
    'nav.profile': 'Profil',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.ok': 'OK',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.submit': 'Senden',
    'common.confirm': 'Bestätigen',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    
    // Home Screen
    'home.welcome': 'Willkommen zurück,',
    'home.newRequest': 'Neue Anfrage',
    'home.getHelpNow': 'Jetzt Hilfe holen',
    'home.browseRequests': 'Anfragen durchsuchen',
    'home.findNewJobs': 'Neue Jobs finden',
    'home.availableRequests': 'Verfügbare Anfragen',
    'home.recentRequests': 'Aktuelle Anfragen',
    'home.recentJobs': 'Aktuelle Jobs',
    'home.noRequestsYet': 'Noch keine Anfragen',
    'home.noJobsYet': 'Noch keine Jobs',
    'home.createFirstRequest': 'Erstellen Sie Ihre erste Anfrage, um zu beginnen',
    'home.browseAvailableRequests': 'Durchsuchen Sie verfügbare Anfragen, um zu beginnen',
    'home.createRequest': 'Anfrage erstellen',
    'home.tapToView': 'Tippen Sie, um Details zu sehen',
    'home.referFriend': 'Freund empfehlen & 10$ verdienen',
    'home.shareRigSnap': 'Teilen Sie RigSnap und werden Sie belohnt, wenn sie beitreten',
    
    // Profile Screen
    'profile.title': 'Profil',
    'profile.personalInformation': 'Persönliche Informationen',
    'profile.name': 'Name',
    'profile.email': 'E-Mail',
    'profile.phone': 'Telefon',
    'profile.location': 'Standort',
    'profile.memberSince': 'Mitglied Seit',
    'profile.truckerInformation': 'LKW-Fahrer Informationen',
    'profile.truckType': 'LKW-Typ',
    'profile.licenseNumber': 'Lizenznummer',
    'profile.serviceProviderInformation': 'Dienstleister Informationen',
    'profile.servicesOffered': 'Angebotene Dienste',
    'profile.serviceRadius': 'Service-Radius',
    'profile.certifications': 'Zertifizierungen',
    'profile.paymentMethods': 'Zahlungsmethoden',
    'profile.settings': 'Einstellungen',
    'profile.accountSettings': 'Kontoeinstellungen',
    'profile.languageRegion': 'Sprache & Region',
    'profile.signOut': 'Abmelden',
    'profile.rating': 'Bewertung',
    'profile.notProvided': 'Nicht angegeben',
    'profile.notSpecified': 'Nicht spezifiziert',
    'profile.miles': 'Meilen',
    'profile.editProfile': 'Profil Bearbeiten',
    'profile.saveChanges': 'Änderungen Speichern',
    'profile.cancel': 'Abbrechen',
    
    // Messages/Chat
    'chat.title': 'Nachrichten',
    'chat.messages': 'Nachrichten',
    'chat.noMessagesYet': 'Noch keine Nachrichten',
    'chat.messagesWillAppear': 'Nachrichten erscheinen hier, wenn Sie mit Dienstleistern chatten',
    'chat.messagesWillAppearProvider': 'Nachrichten erscheinen hier, wenn Sie Serviceanfragen annehmen',
    'chat.active': 'Aktiv',
    'chat.completed': 'Abgeschlossen',
    'chat.typeMessage': 'Nachricht eingeben...',
    'chat.trucker': 'LKW-Fahrer',
    'chat.serviceProvider': 'Dienstleister',
    
    // Leads
    'leads.title': 'Lead-Verfolgung',
    'leads.leadTracking': 'Lead-Verfolgung',
    'leads.monitorLeadFees': 'Überwachen Sie Ihre Lead-Gebühren und Transaktionen',
    'leads.netSpent': 'Netto Ausgegeben',
    'leads.totalLeads': 'Gesamt Leads',
    'leads.refunded': 'Erstattet',
    'leads.penalties': 'Strafen',
    'leads.pending': 'Ausstehend',
    'leads.transactionHistory': 'Transaktionshistorie',
    'leads.noLeadFeesYet': 'Noch keine Lead-Gebühren',
    'leads.leadFeesWillAppear': 'Lead-Gebühren erscheinen hier, wenn Dienstleister Ihre Anfragen annehmen',
    'leads.leadFeesWillAppearProvider': 'Lead-Gebühren erscheinen hier, wenn Sie Serviceanfragen annehmen',
    
    // Account Settings
    'settings.title': 'Kontoeinstellungen',
    'settings.security': 'Sicherheit',
    'settings.changePassword': 'Passwort Ändern',
    'settings.updatePassword': 'Aktualisieren Sie Ihr Kontopasswort',
    'settings.languageRegion': 'Sprache & Region',
    'settings.language': 'Sprache',
    'settings.currentLanguage': 'Aktuell',
    'settings.notifications': 'Benachrichtigungen',
    'settings.pushNotifications': 'Push-Benachrichtigungen',
    'settings.emailNotifications': 'E-Mail-Benachrichtigungen',
    'settings.smsNotifications': 'SMS-Benachrichtigungen',
    'settings.requestUpdates': 'Anfrage-Updates',
    'settings.securityAlerts': 'Sicherheitswarnungen',
    'settings.marketingEmails': 'Marketing-E-Mails',
    'settings.appPreferences': 'App-Einstellungen',
    'settings.darkMode': 'Dunkler Modus',
    'settings.support': 'Support',
    'settings.helpCenter': 'Hilfezentrum',
    'settings.privacyPolicy': 'Datenschutzrichtlinie',
    'settings.dangerZone': 'Gefahrenzone',
    'settings.deleteAccount': 'Konto Löschen',
    
    // Service Types
    'service.towing': 'Abschleppdienst',
    'service.repair': 'Straßendienst',
    'service.mechanic': 'Mechaniker-Service',
    'service.tireRepair': 'Mobile Reifenreparatur',
    'service.truckWash': 'Mobile LKW-Wäsche',
    'service.hoseRepair': 'Schlauch-Reparatur',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.messages': 'Сообщения',
    'nav.leads': 'Лиды',
    'nav.profile': 'Профиль',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.cancel': 'Отмена',
    'common.ok': 'ОК',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.close': 'Закрыть',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.previous': 'Предыдущий',
    'common.submit': 'Отправить',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    
    // Home Screen
    'home.welcome': 'Добро пожаловать,',
    'home.newRequest': 'Новый Запрос',
    'home.getHelpNow': 'Получить помощь сейчас',
    'home.browseRequests': 'Просмотр Запросов',
    'home.findNewJobs': 'Найти новые работы',
    'home.availableRequests': 'Доступные Запросы',
    'home.recentRequests': 'Недавние Запросы',
    'home.recentJobs': 'Недавние Работы',
    'home.noRequestsYet': 'Пока нет запросов',
    'home.noJobsYet': 'Пока нет работ',
    'home.createFirstRequest': 'Создайте свой первый запрос, чтобы начать',
    'home.browseAvailableRequests': 'Просмотрите доступные запросы, чтобы начать',
    'home.createRequest': 'Создать Запрос',
    'home.tapToView': 'Нажмите, чтобы посмотреть детали',
    'home.referFriend': 'Пригласите друга и заработайте $10',
    'home.shareRigSnap': 'Поделитесь RigSnap и получите вознаграждение, когда они присоединятся',
    
    // Profile Screen
    'profile.title': 'Профиль',
    'profile.personalInformation': 'Личная Информация',
    'profile.name': 'Имя',
    'profile.email': 'Email',
    'profile.phone': 'Телефон',
    'profile.location': 'Местоположение',
    'profile.memberSince': 'Участник С',
    'profile.truckerInformation': 'Информация о Водителе',
    'profile.truckType': 'Тип Грузовика',
    'profile.licenseNumber': 'Номер Лицензии',
    'profile.serviceProviderInformation': 'Информация о Поставщике Услуг',
    'profile.servicesOffered': 'Предлагаемые Услуги',
    'profile.serviceRadius': 'Радиус Обслуживания',
    'profile.certifications': 'Сертификаты',
    'profile.paymentMethods': 'Способы Оплаты',
    'profile.settings': 'Настройки',
    'profile.accountSettings': 'Настройки Аккаунта',
    'profile.languageRegion': 'Язык и Регион',
    'profile.signOut': 'Выйти',
    'profile.rating': 'рейтинг',
    'profile.notProvided': 'Не указано',
    'profile.notSpecified': 'Не определено',
    'profile.miles': 'миль',
    'profile.editProfile': 'Редактировать Профиль',
    'profile.saveChanges': 'Сохранить Изменения',
    'profile.cancel': 'Отмена',
    
    // Messages/Chat
    'chat.title': 'Сообщения',
    'chat.messages': 'Сообщения',
    'chat.noMessagesYet': 'Пока нет сообщений',
    'chat.messagesWillAppear': 'Сообщения появятся здесь, когда вы начнете общаться с поставщиками услуг',
    'chat.messagesWillAppearProvider': 'Сообщения появятся здесь, когда вы примете запросы на обслуживание',
    'chat.active': 'Активный',
    'chat.completed': 'Завершено',
    'chat.typeMessage': 'Введите сообщение...',
    'chat.trucker': 'Водитель',
    'chat.serviceProvider': 'Поставщик Услуг',
    
    // Leads
    'leads.title': 'Отслеживание Лидов',
    'leads.leadTracking': 'Отслеживание Лидов',
    'leads.monitorLeadFees': 'Отслеживайте ваши комиссии за лиды и транзакции',
    'leads.netSpent': 'Чистые Расходы',
    'leads.totalLeads': 'Всего Лидов',
    'leads.refunded': 'Возвращено',
    'leads.penalties': 'Штрафы',
    'leads.pending': 'В Ожидании',
    'leads.transactionHistory': 'История Транзакций',
    'leads.noLeadFeesYet': 'Пока нет комиссий за лиды',
    'leads.leadFeesWillAppear': 'Комиссии за лиды появятся здесь, когда поставщики услуг примут ваши запросы',
    'leads.leadFeesWillAppearProvider': 'Комиссии за лиды появятся здесь, когда вы примете запросы на обслуживание',
    
    // Account Settings
    'settings.title': 'Настройки Аккаунта',
    'settings.security': 'Безопасность',
    'settings.changePassword': 'Изменить Пароль',
    'settings.updatePassword': 'Обновите пароль вашего аккаунта',
    'settings.languageRegion': 'Язык и Регион',
    'settings.language': 'Язык',
    'settings.currentLanguage': 'Текущий',
    'settings.notifications': 'Уведомления',
    'settings.pushNotifications': 'Push-уведомления',
    'settings.emailNotifications': 'Email-уведомления',
    'settings.smsNotifications': 'SMS-уведомления',
    'settings.requestUpdates': 'Обновления Запросов',
    'settings.securityAlerts': 'Оповещения Безопасности',
    'settings.marketingEmails': 'Маркетинговые Email',
    'settings.appPreferences': 'Настройки Приложения',
    'settings.darkMode': 'Темный Режим',
    'settings.support': 'Поддержка',
    'settings.helpCenter': 'Центр Помощи',
    'settings.privacyPolicy': 'Политика Конфиденциальности',
    'settings.dangerZone': 'Опасная Зона',
    'settings.deleteAccount': 'Удалить Аккаунт',
    
    // Service Types
    'service.towing': 'Служба Эвакуации',
    'service.repair': 'Дорожная Служба',
    'service.mechanic': 'Механическая Служба',
    'service.tireRepair': 'Мобильный Ремонт Шин',
    'service.truckWash': 'Мобильная Мойка Грузовиков',
    'service.hoseRepair': 'Ремонт Шлангов',
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.messages': 'Messaggi',
    'nav.leads': 'Lead',
    'nav.profile': 'Profilo',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.cancel': 'Annulla',
    'common.ok': 'OK',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.close': 'Chiudi',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.previous': 'Precedente',
    'common.submit': 'Invia',
    'common.confirm': 'Conferma',
    'common.yes': 'Sì',
    'common.no': 'No',
    
    // Home Screen
    'home.welcome': 'Bentornato,',
    'home.newRequest': 'Nuova Richiesta',
    'home.getHelpNow': 'Ottieni aiuto ora',
    'home.browseRequests': 'Sfoglia Richieste',
    'home.findNewJobs': 'Trova nuovi lavori',
    'home.availableRequests': 'Richieste Disponibili',
    'home.recentRequests': 'Richieste Recenti',
    'home.recentJobs': 'Lavori Recenti',
    'home.noRequestsYet': 'Nessuna richiesta ancora',
    'home.noJobsYet': 'Nessun lavoro ancora',
    'home.createFirstRequest': 'Crea la tua prima richiesta per iniziare',
    'home.browseAvailableRequests': 'Sfoglia le richieste disponibili per iniziare',
    'home.createRequest': 'Crea Richiesta',
    'home.tapToView': 'Tocca per vedere i dettagli',
    'home.referFriend': 'Invita un Amico e Guadagna $10',
    'home.shareRigSnap': 'Condividi RigSnap e ottieni ricompense quando si uniscono',
    
    // Profile Screen
    'profile.title': 'Profilo',
    'profile.personalInformation': 'Informazioni Personali',
    'profile.name': 'Nome',
    'profile.email': 'Email',
    'profile.phone': 'Telefono',
    'profile.location': 'Posizione',
    'profile.memberSince': 'Membro Dal',
    'profile.truckerInformation': 'Informazioni Camionista',
    'profile.truckType': 'Tipo di Camion',
    'profile.licenseNumber': 'Numero di Licenza',
    'profile.serviceProviderInformation': 'Informazioni Fornitore di Servizi',
    'profile.servicesOffered': 'Servizi Offerti',
    'profile.serviceRadius': 'Raggio di Servizio',
    'profile.certifications': 'Certificazioni',
    'profile.paymentMethods': 'Metodi di Pagamento',
    'profile.settings': 'Impostazioni',
    'profile.accountSettings': 'Impostazioni Account',
    'profile.languageRegion': 'Lingua e Regione',
    'profile.signOut': 'Disconnetti',
    'profile.rating': 'valutazione',
    'profile.notProvided': 'Non fornito',
    'profile.notSpecified': 'Non specificato',
    'profile.miles': 'miglia',
    'profile.editProfile': 'Modifica Profilo',
    'profile.saveChanges': 'Salva Modifiche',
    'profile.cancel': 'Annulla',
    
    // Messages/Chat
    'chat.title': 'Messaggi',
    'chat.messages': 'Messaggi',
    'chat.noMessagesYet': 'Nessun messaggio ancora',
    'chat.messagesWillAppear': 'I messaggi appariranno qui quando inizierai a chattare con i fornitori di servizi',
    'chat.messagesWillAppearProvider': 'I messaggi appariranno qui quando accetterai richieste di servizio',
    'chat.active': 'Attivo',
    'chat.completed': 'Completato',
    'chat.typeMessage': 'Scrivi un messaggio...',
    'chat.trucker': 'Camionista',
    'chat.serviceProvider': 'Fornitore di Servizi',
    
    // Leads
    'leads.title': 'Tracciamento Lead',
    'leads.leadTracking': 'Tracciamento Lead',
    'leads.monitorLeadFees': 'Monitora le tue commissioni lead e transazioni',
    'leads.netSpent': 'Spesa Netta',
    'leads.totalLeads': 'Lead Totali',
    'leads.refunded': 'Rimborsato',
    'leads.penalties': 'Penalità',
    'leads.pending': 'In Attesa',
    'leads.transactionHistory': 'Cronologia Transazioni',
    'leads.noLeadFeesYet': 'Nessuna commissione lead ancora',
    'leads.leadFeesWillAppear': 'Le commissioni lead appariranno qui quando i fornitori di servizi accetteranno le tue richieste',
    'leads.leadFeesWillAppearProvider': 'Le commissioni lead appariranno qui quando accetterai richieste di servizio',
    
    // Account Settings
    'settings.title': 'Impostazioni Account',
    'settings.security': 'Sicurezza',
    'settings.changePassword': 'Cambia Password',
    'settings.updatePassword': 'Aggiorna la password del tuo account',
    'settings.languageRegion': 'Lingua e Regione',
    'settings.language': 'Lingua',
    'settings.currentLanguage': 'Attuale',
    'settings.notifications': 'Notifiche',
    'settings.pushNotifications': 'Notifiche Push',
    'settings.emailNotifications': 'Notifiche Email',
    'settings.smsNotifications': 'Notifiche SMS',
    'settings.requestUpdates': 'Aggiornamenti Richieste',
    'settings.securityAlerts': 'Avvisi di Sicurezza',
    'settings.marketingEmails': 'Email Marketing',
    'settings.appPreferences': 'Preferenze App',
    'settings.darkMode': 'Modalità Scura',
    'settings.support': 'Supporto',
    'settings.helpCenter': 'Centro Assistenza',
    'settings.privacyPolicy': 'Informativa Privacy',
    'settings.dangerZone': 'Zona Pericolosa',
    'settings.deleteAccount': 'Elimina Account',
    
    // Service Types
    'service.towing': 'Servizio di Traino',
    'service.repair': 'Servizio Stradale',
    'service.mechanic': 'Servizio Meccanico',
    'service.tireRepair': 'Riparazione Mobile Pneumatici',
    'service.truckWash': 'Lavaggio Mobile Camion',
    'service.hoseRepair': 'Riparazione Tubi',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.messages': 'Mensagens',
    'nav.leads': 'Leads',
    'nav.profile': 'Perfil',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.ok': 'OK',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.close': 'Fechar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.submit': 'Enviar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    
    // Home Screen
    'home.welcome': 'Bem-vindo de volta,',
    'home.newRequest': 'Nova Solicitação',
    'home.getHelpNow': 'Obter ajuda agora',
    'home.browseRequests': 'Navegar Solicitações',
    'home.findNewJobs': 'Encontrar novos trabalhos',
    'home.availableRequests': 'Solicitações Disponíveis',
    'home.recentRequests': 'Solicitações Recentes',
    'home.recentJobs': 'Trabalhos Recentes',
    'home.noRequestsYet': 'Nenhuma solicitação ainda',
    'home.noJobsYet': 'Nenhum trabalho ainda',
    'home.createFirstRequest': 'Crie sua primeira solicitação para começar',
    'home.browseAvailableRequests': 'Navegue pelas solicitações disponíveis para começar',
    'home.createRequest': 'Criar Solicitação',
    'home.tapToView': 'Toque para ver detalhes',
    'home.referFriend': 'Indique um Amigo e Ganhe $10',
    'home.shareRigSnap': 'Compartilhe RigSnap e seja recompensado quando eles se juntarem',
    
    // Profile Screen
    'profile.title': 'Perfil',
    'profile.personalInformation': 'Informações Pessoais',
    'profile.name': 'Nome',
    'profile.email': 'Email',
    'profile.phone': 'Telefone',
    'profile.location': 'Localização',
    'profile.memberSince': 'Membro Desde',
    'profile.truckerInformation': 'Informações do Caminhoneiro',
    'profile.truckType': 'Tipo de Caminhão',
    'profile.licenseNumber': 'Número da Licença',
    'profile.serviceProviderInformation': 'Informações do Provedor de Serviços',
    'profile.servicesOffered': 'Serviços Oferecidos',
    'profile.serviceRadius': 'Raio de Serviço',
    'profile.certifications': 'Certificações',
    'profile.paymentMethods': 'Métodos de Pagamento',
    'profile.settings': 'Configurações',
    'profile.accountSettings': 'Configurações da Conta',
    'profile.languageRegion': 'Idioma e Região',
    'profile.signOut': 'Sair',
    'profile.rating': 'avaliação',
    'profile.notProvided': 'Não fornecido',
    'profile.notSpecified': 'Não especificado',
    'profile.miles': 'milhas',
    'profile.editProfile': 'Editar Perfil',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.cancel': 'Cancelar',
    
    // Messages/Chat
    'chat.title': 'Mensagens',
    'chat.messages': 'Mensagens',
    'chat.noMessagesYet': 'Nenhuma mensagem ainda',
    'chat.messagesWillAppear': 'As mensagens aparecerão aqui quando você começar a conversar com provedores de serviços',
    'chat.messagesWillAppearProvider': 'As mensagens aparecerão aqui quando você aceitar solicitações de serviço',
    'chat.active': 'Ativo',
    'chat.completed': 'Concluído',
    'chat.typeMessage': 'Digite uma mensagem...',
    'chat.trucker': 'Caminhoneiro',
    'chat.serviceProvider': 'Provedor de Serviços',
    
    // Leads
    'leads.title': 'Rastreamento de Leads',
    'leads.leadTracking': 'Rastreamento de Leads',
    'leads.monitorLeadFees': 'Monitore suas taxas de leads e transações',
    'leads.netSpent': 'Gasto Líquido',
    'leads.totalLeads': 'Total de Leads',
    'leads.refunded': 'Reembolsado',
    'leads.penalties': 'Penalidades',
    'leads.pending': 'Pendente',
    'leads.transactionHistory': 'Histórico de Transações',
    'leads.noLeadFeesYet': 'Nenhuma taxa de lead ainda',
    'leads.leadFeesWillAppear': 'As taxas de leads aparecerão aqui quando os provedores de serviços aceitarem suas solicitações',
    'leads.leadFeesWillAppearProvider': 'As taxas de leads aparecerão aqui quando você aceitar solicitações de serviço',
    
    // Account Settings
    'settings.title': 'Configurações da Conta',
    'settings.security': 'Segurança',
    'settings.changePassword': 'Alterar Senha',
    'settings.updatePassword': 'Atualize a senha da sua conta',
    'settings.languageRegion': 'Idioma e Região',
    'settings.language': 'Idioma',
    'settings.currentLanguage': 'Atual',
    'settings.notifications': 'Notificações',
    'settings.pushNotifications': 'Notificações Push',
    'settings.emailNotifications': 'Notificações por Email',
    'settings.smsNotifications': 'Notificações SMS',
    'settings.requestUpdates': 'Atualizações de Solicitações',
    'settings.securityAlerts': 'Alertas de Segurança',
    'settings.marketingEmails': 'Emails de Marketing',
    'settings.appPreferences': 'Preferências do App',
    'settings.darkMode': 'Modo Escuro',
    'settings.support': 'Suporte',
    'settings.helpCenter': 'Central de Ajuda',
    'settings.privacyPolicy': 'Política de Privacidade',
    'settings.dangerZone': 'Zona de Perigo',
    'settings.deleteAccount': 'Excluir Conta',
    
    // Service Types
    'service.towing': 'Serviço de Reboque',
    'service.repair': 'Serviço Rodoviário',
    'service.mechanic': 'Serviço Mecânico',
    'service.tireRepair': 'Reparo Móvel de Pneus',
    'service.truckWash': 'Lavagem Móvel de Caminhões',
    'service.hoseRepair': 'Reparo de Mangueiras',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.messages': '消息',
    'nav.leads': '客户',
    'nav.profile': '个人资料',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.ok': '确定',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.close': '关闭',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.submit': '提交',
    'common.confirm': '确认',
    'common.yes': '是',
    'common.no': '否',
    
    // Home Screen
    'home.welcome': '欢迎回来，',
    'home.newRequest': '新请求',
    'home.getHelpNow': '立即获取帮助',
    'home.browseRequests': '浏览请求',
    'home.findNewJobs': '寻找新工作',
    'home.availableRequests': '可用请求',
    'home.recentRequests': '最近请求',
    'home.recentJobs': '最近工作',
    'home.noRequestsYet': '暂无请求',
    'home.noJobsYet': '暂无工作',
    'home.createFirstRequest': '创建您的第一个请求开始',
    'home.browseAvailableRequests': '浏览可用请求开始',
    'home.createRequest': '创建请求',
    'home.tapToView': '点击查看详情',
    'home.referFriend': '推荐朋友赚取$10',
    'home.shareRigSnap': '分享RigSnap，当他们加入时获得奖励',
    
    // Profile Screen
    'profile.title': '个人资料',
    'profile.personalInformation': '个人信息',
    'profile.name': '姓名',
    'profile.email': '邮箱',
    'profile.phone': '电话',
    'profile.location': '位置',
    'profile.memberSince': '注册时间',
    'profile.truckerInformation': '卡车司机信息',
    'profile.truckType': '卡车类型',
    'profile.licenseNumber': '执照号码',
    'profile.serviceProviderInformation': '服务提供商信息',
    'profile.servicesOffered': '提供的服务',
    'profile.serviceRadius': '服务半径',
    'profile.certifications': '认证',
    'profile.paymentMethods': '支付方式',
    'profile.settings': '设置',
    'profile.accountSettings': '账户设置',
    'profile.languageRegion': '语言和地区',
    'profile.signOut': '退出登录',
    'profile.rating': '评分',
    'profile.notProvided': '未提供',
    'profile.notSpecified': '未指定',
    'profile.miles': '英里',
    'profile.editProfile': '编辑个人资料',
    'profile.saveChanges': '保存更改',
    'profile.cancel': '取消',
    
    // Messages/Chat
    'chat.title': '消息',
    'chat.messages': '消息',
    'chat.noMessagesYet': '暂无消息',
    'chat.messagesWillAppear': '当您开始与服务提供商聊天时，消息将出现在这里',
    'chat.messagesWillAppearProvider': '当您接受服务请求时，消息将出现在这里',
    'chat.active': '活跃',
    'chat.completed': '已完成',
    'chat.typeMessage': '输入消息...',
    'chat.trucker': '卡车司机',
    'chat.serviceProvider': '服务提供商',
    
    // Leads
    'leads.title': '客户跟踪',
    'leads.leadTracking': '客户跟踪',
    'leads.monitorLeadFees': '监控您的客户费用和交易',
    'leads.netSpent': '净支出',
    'leads.totalLeads': '总客户数',
    'leads.refunded': '已退款',
    'leads.penalties': '罚款',
    'leads.pending': '待处理',
    'leads.transactionHistory': '交易历史',
    'leads.noLeadFeesYet': '暂无客户费用',
    'leads.leadFeesWillAppear': '当服务提供商接受您的请求时，客户费用将出现在这里',
    'leads.leadFeesWillAppearProvider': '当您接受服务请求时，客户费用将出现在这里',
    
    // Account Settings
    'settings.title': '账户设置',
    'settings.security': '安全',
    'settings.changePassword': '更改密码',
    'settings.updatePassword': '更新您的账户密码',
    'settings.languageRegion': '语言和地区',
    'settings.language': '语言',
    'settings.currentLanguage': '当前',
    'settings.notifications': '通知',
    'settings.pushNotifications': '推送通知',
    'settings.emailNotifications': '邮件通知',
    'settings.smsNotifications': '短信通知',
    'settings.requestUpdates': '请求更新',
    'settings.securityAlerts': '安全警报',
    'settings.marketingEmails': '营销邮件',
    'settings.appPreferences': '应用偏好',
    'settings.darkMode': '深色模式',
    'settings.support': '支持',
    'settings.helpCenter': '帮助中心',
    'settings.privacyPolicy': '隐私政策',
    'settings.dangerZone': '危险区域',
    'settings.deleteAccount': '删除账户',
    
    // Service Types
    'service.towing': '拖车服务',
    'service.repair': '道路服务',
    'service.mechanic': '机械服务',
    'service.tireRepair': '移动轮胎维修',
    'service.truckWash': '移动卡车清洗',
    'service.hoseRepair': '软管维修',
  },
  ja: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.messages': 'メッセージ',
    'nav.leads': 'リード',
    'nav.profile': 'プロフィール',
    
    // Common
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.cancel': 'キャンセル',
    'common.ok': 'OK',
    'common.save': '保存',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.close': '閉じる',
    'common.back': '戻る',
    'common.next': '次へ',
    'common.previous': '前へ',
    'common.submit': '送信',
    'common.confirm': '確認',
    'common.yes': 'はい',
    'common.no': 'いいえ',
    
    // Home Screen
    'home.welcome': 'おかえりなさい、',
    'home.newRequest': '新しいリクエスト',
    'home.getHelpNow': '今すぐヘルプを取得',
    'home.browseRequests': 'リクエストを閲覧',
    'home.findNewJobs': '新しい仕事を見つける',
    'home.availableRequests': '利用可能なリクエスト',
    'home.recentRequests': '最近のリクエスト',
    'home.recentJobs': '最近の仕事',
    'home.noRequestsYet': 'まだリクエストがありません',
    'home.noJobsYet': 'まだ仕事がありません',
    'home.createFirstRequest': '最初のリクエストを作成して開始',
    'home.browseAvailableRequests': '利用可能なリクエストを閲覧して開始',
    'home.createRequest': 'リクエストを作成',
    'home.tapToView': 'タップして詳細を表示',
    'home.referFriend': '友達を紹介して$10獲得',
    'home.shareRigSnap': 'RigSnapを共有して、参加時に報酬を獲得',
    
    // Profile Screen
    'profile.title': 'プロフィール',
    'profile.personalInformation': '個人情報',
    'profile.name': '名前',
    'profile.email': 'メール',
    'profile.phone': '電話',
    'profile.location': '場所',
    'profile.memberSince': 'メンバー歴',
    'profile.truckerInformation': 'トラック運転手情報',
    'profile.truckType': 'トラックタイプ',
    'profile.licenseNumber': 'ライセンス番号',
    'profile.serviceProviderInformation': 'サービスプロバイダー情報',
    'profile.servicesOffered': '提供サービス',
    'profile.serviceRadius': 'サービス範囲',
    'profile.certifications': '認定',
    'profile.paymentMethods': '支払い方法',
    'profile.settings': '設定',
    'profile.accountSettings': 'アカウント設定',
    'profile.languageRegion': '言語と地域',
    'profile.signOut': 'サインアウト',
    'profile.rating': '評価',
    'profile.notProvided': '未提供',
    'profile.notSpecified': '未指定',
    'profile.miles': 'マイル',
    'profile.editProfile': 'プロフィール編集',
    'profile.saveChanges': '変更を保存',
    'profile.cancel': 'キャンセル',
    
    // Messages/Chat
    'chat.title': 'メッセージ',
    'chat.messages': 'メッセージ',
    'chat.noMessagesYet': 'まだメッセージがありません',
    'chat.messagesWillAppear': 'サービスプロバイダーとチャットを始めるとメッセージがここに表示されます',
    'chat.messagesWillAppearProvider': 'サービスリクエストを受け入れるとメッセージがここに表示されます',
    'chat.active': 'アクティブ',
    'chat.completed': '完了',
    'chat.typeMessage': 'メッセージを入力...',
    'chat.trucker': 'トラック運転手',
    'chat.serviceProvider': 'サービスプロバイダー',
    
    // Leads
    'leads.title': 'リード追跡',
    'leads.leadTracking': 'リード追跡',
    'leads.monitorLeadFees': 'リード料金と取引を監視',
    'leads.netSpent': '純支出',
    'leads.totalLeads': '総リード数',
    'leads.refunded': '返金済み',
    'leads.penalties': 'ペナルティ',
    'leads.pending': '保留中',
    'leads.transactionHistory': '取引履歴',
    'leads.noLeadFeesYet': 'まだリード料金がありません',
    'leads.leadFeesWillAppear': 'サービスプロバイダーがあなたのリクエストを受け入れるとリード料金がここに表示されます',
    'leads.leadFeesWillAppearProvider': 'サービスリクエストを受け入れるとリード料金がここに表示されます',
    
    // Account Settings
    'settings.title': 'アカウント設定',
    'settings.security': 'セキュリティ',
    'settings.changePassword': 'パスワード変更',
    'settings.updatePassword': 'アカウントパスワードを更新',
    'settings.languageRegion': '言語と地域',
    'settings.language': '言語',
    'settings.currentLanguage': '現在',
    'settings.notifications': '通知',
    'settings.pushNotifications': 'プッシュ通知',
    'settings.emailNotifications': 'メール通知',
    'settings.smsNotifications': 'SMS通知',
    'settings.requestUpdates': 'リクエスト更新',
    'settings.securityAlerts': 'セキュリティアラート',
    'settings.marketingEmails': 'マーケティングメール',
    'settings.appPreferences': 'アプリ設定',
    'settings.darkMode': 'ダークモード',
    'settings.support': 'サポート',
    'settings.helpCenter': 'ヘルプセンター',
    'settings.privacyPolicy': 'プライバシーポリシー',
    'settings.dangerZone': '危険ゾーン',
    'settings.deleteAccount': 'アカウント削除',
    
    // Service Types
    'service.towing': 'けん引サービス',
    'service.repair': '道路サービス',
    'service.mechanic': '整備サービス',
    'service.tireRepair': 'モバイルタイヤ修理',
    'service.truckWash': 'モバイルトラック洗車',
    'service.hoseRepair': 'ホース修理',
  },
  ko: {
    // Navigation
    'nav.home': '홈',
    'nav.messages': '메시지',
    'nav.leads': '리드',
    'nav.profile': '프로필',
    
    // Common
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.success': '성공',
    'common.cancel': '취소',
    'common.ok': '확인',
    'common.save': '저장',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.close': '닫기',
    'common.back': '뒤로',
    'common.next': '다음',
    'common.previous': '이전',
    'common.submit': '제출',
    'common.confirm': '확인',
    'common.yes': '예',
    'common.no': '아니오',
    
    // Home Screen
    'home.welcome': '다시 오신 것을 환영합니다,',
    'home.newRequest': '새 요청',
    'home.getHelpNow': '지금 도움 받기',
    'home.browseRequests': '요청 찾아보기',
    'home.findNewJobs': '새 작업 찾기',
    'home.availableRequests': '사용 가능한 요청',
    'home.recentRequests': '최근 요청',
    'home.recentJobs': '최근 작업',
    'home.noRequestsYet': '아직 요청이 없습니다',
    'home.noJobsYet': '아직 작업이 없습니다',
    'home.createFirstRequest': '첫 번째 요청을 만들어 시작하세요',
    'home.browseAvailableRequests': '사용 가능한 요청을 찾아보며 시작하세요',
    'home.createRequest': '요청 만들기',
    'home.tapToView': '자세히 보려면 탭하세요',
    'home.referFriend': '친구 추천하고 $10 받기',
    'home.shareRigSnap': 'RigSnap을 공유하고 가입 시 보상 받기',
    
    // Profile Screen
    'profile.title': '프로필',
    'profile.personalInformation': '개인 정보',
    'profile.name': '이름',
    'profile.email': '이메일',
    'profile.phone': '전화',
    'profile.location': '위치',
    'profile.memberSince': '가입일',
    'profile.truckerInformation': '트럭 운전사 정보',
    'profile.truckType': '트럭 유형',
    'profile.licenseNumber': '면허 번호',
    'profile.serviceProviderInformation': '서비스 제공업체 정보',
    'profile.servicesOffered': '제공 서비스',
    'profile.serviceRadius': '서비스 반경',
    'profile.certifications': '인증',
    'profile.paymentMethods': '결제 방법',
    'profile.settings': '설정',
    'profile.accountSettings': '계정 설정',
    'profile.languageRegion': '언어 및 지역',
    'profile.signOut': '로그아웃',
    'profile.rating': '평점',
    'profile.notProvided': '제공되지 않음',
    'profile.notSpecified': '지정되지 않음',
    'profile.miles': '마일',
    'profile.editProfile': '프로필 편집',
    'profile.saveChanges': '변경사항 저장',
    'profile.cancel': '취소',
    
    // Messages/Chat
    'chat.title': '메시지',
    'chat.messages': '메시지',
    'chat.noMessagesYet': '아직 메시지가 없습니다',
    'chat.messagesWillAppear': '서비스 제공업체와 채팅을 시작하면 메시지가 여기에 나타납니다',
    'chat.messagesWillAppearProvider': '서비스 요청을 수락하면 메시지가 여기에 나타납니다',
    'chat.active': '활성',
    'chat.completed': '완료',
    'chat.typeMessage': '메시지 입력...',
    'chat.trucker': '트럭 운전사',
    'chat.serviceProvider': '서비스 제공업체',
    
    // Leads
    'leads.title': '리드 추적',
    'leads.leadTracking': '리드 추적',
    'leads.monitorLeadFees': '리드 수수료 및 거래 모니터링',
    'leads.netSpent': '순 지출',
    'leads.totalLeads': '총 리드',
    'leads.refunded': '환불됨',
    'leads.penalties': '벌금',
    'leads.pending': '대기 중',
    'leads.transactionHistory': '거래 내역',
    'leads.noLeadFeesYet': '아직 리드 수수료가 없습니다',
    'leads.leadFeesWillAppear': '서비스 제공업체가 요청을 수락하면 리드 수수료가 여기에 나타납니다',
    'leads.leadFeesWillAppearProvider': '서비스 요청을 수락하면 리드 수수료가 여기에 나타납니다',
    
    // Account Settings
    'settings.title': '계정 설정',
    'settings.security': '보안',
    'settings.changePassword': '비밀번호 변경',
    'settings.updatePassword': '계정 비밀번호 업데이트',
    'settings.languageRegion': '언어 및 지역',
    'settings.language': '언어',
    'settings.currentLanguage': '현재',
    'settings.notifications': '알림',
    'settings.pushNotifications': '푸시 알림',
    'settings.emailNotifications': '이메일 알림',
    'settings.smsNotifications': 'SMS 알림',
    'settings.requestUpdates': '요청 업데이트',
    'settings.securityAlerts': '보안 경고',
    'settings.marketingEmails': '마케팅 이메일',
    'settings.appPreferences': '앱 설정',
    'settings.darkMode': '다크 모드',
    'settings.support': '지원',
    'settings.helpCenter': '도움말 센터',
    'settings.privacyPolicy': '개인정보 처리방침',
    'settings.dangerZone': '위험 구역',
    'settings.deleteAccount': '계정 삭제',
    
    // Service Types
    'service.towing': '견인 서비스',
    'service.repair': '도로 서비스',
    'service.mechanic': '정비 서비스',
    'service.tireRepair': '모바일 타이어 수리',
    'service.truckWash': '모바일 트럭 세차',
    'service.hoseRepair': '호스 수리',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.messages': 'الرسائل',
    'nav.leads': 'العملاء المحتملون',
    'nav.profile': 'الملف الشخصي',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.ok': 'موافق',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    
    // Home Screen
    'home.welcome': 'مرحباً بعودتك،',
    'home.newRequest': 'طلب جديد',
    'home.getHelpNow': 'احصل على المساعدة الآن',
    'home.browseRequests': 'تصفح الطلبات',
    'home.findNewJobs': 'العثور على وظائف جديدة',
    'home.availableRequests': 'الطلبات المتاحة',
    'home.recentRequests': 'الطلبات الأخيرة',
    'home.recentJobs': 'الوظائف الأخيرة',
    'home.noRequestsYet': 'لا توجد طلبات بعد',
    'home.noJobsYet': 'لا توجد وظائف بعد',
    'home.createFirstRequest': 'أنشئ طلبك الأول للبدء',
    'home.browseAvailableRequests': 'تصفح الطلبات المتاحة للبدء',
    'home.createRequest': 'إنشاء طلب',
    'home.tapToView': 'اضغط لعرض التفاصيل',
    'home.referFriend': 'أحل صديق واكسب $10',
    'home.shareRigSnap': 'شارك RigSnap واحصل على مكافآت عند انضمامهم',
    
    // Profile Screen
    'profile.title': 'الملف الشخصي',
    'profile.personalInformation': 'المعلومات الشخصية',
    'profile.name': 'الاسم',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'الهاتف',
    'profile.location': 'الموقع',
    'profile.memberSince': 'عضو منذ',
    'profile.truckerInformation': 'معلومات سائق الشاحنة',
    'profile.truckType': 'نوع الشاحنة',
    'profile.licenseNumber': 'رقم الرخصة',
    'profile.serviceProviderInformation': 'معلومات مقدم الخدمة',
    'profile.servicesOffered': 'الخدمات المقدمة',
    'profile.serviceRadius': 'نطاق الخدمة',
    'profile.certifications': 'الشهادات',
    'profile.paymentMethods': 'طرق الدفع',
    'profile.settings': 'الإعدادات',
    'profile.accountSettings': 'إعدادات الحساب',
    'profile.languageRegion': 'اللغة والمنطقة',
    'profile.signOut': 'تسجيل الخروج',
    'profile.rating': 'التقييم',
    'profile.notProvided': 'غير مقدم',
    'profile.notSpecified': 'غير محدد',
    'profile.miles': 'أميال',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.cancel': 'إلغاء',
    
    // Messages/Chat
    'chat.title': 'الرسائل',
    'chat.messages': 'الرسائل',
    'chat.noMessagesYet': 'لا توجد رسائل بعد',
    'chat.messagesWillAppear': 'ستظهر الرسائل هنا عندما تبدأ المحادثة مع مقدمي الخدمات',
    'chat.messagesWillAppearProvider': 'ستظهر الرسائل هنا عندما تقبل طلبات الخدمة',
    'chat.active': 'نشط',
    'chat.completed': 'مكتمل',
    'chat.typeMessage': 'اكتب رسالة...',
    'chat.trucker': 'سائق الشاحنة',
    'chat.serviceProvider': 'مقدم الخدمة',
    
    // Leads
    'leads.title': 'تتبع العملاء المحتملين',
    'leads.leadTracking': 'تتبع العملاء المحتملين',
    'leads.monitorLeadFees': 'راقب رسوم العملاء المحتملين والمعاملات',
    'leads.netSpent': 'صافي الإنفاق',
    'leads.totalLeads': 'إجمالي العملاء المحتملين',
    'leads.refunded': 'مسترد',
    'leads.penalties': 'الغرامات',
    'leads.pending': 'في الانتظار',
    'leads.transactionHistory': 'تاريخ المعاملات',
    'leads.noLeadFeesYet': 'لا توجد رسوم عملاء محتملين بعد',
    'leads.leadFeesWillAppear': 'ستظهر رسوم العملاء المحتملين هنا عندما يقبل مقدمو الخدمات طلباتك',
    'leads.leadFeesWillAppearProvider': 'ستظهر رسوم العملاء المحتملين هنا عندما تقبل طلبات الخدمة',
    
    // Account Settings
    'settings.title': 'إعدادات الحساب',
    'settings.security': 'الأمان',
    'settings.changePassword': 'تغيير كلمة المرور',
    'settings.updatePassword': 'تحديث كلمة مرور حسابك',
    'settings.languageRegion': 'اللغة والمنطقة',
    'settings.language': 'اللغة',
    'settings.currentLanguage': 'الحالية',
    'settings.notifications': 'الإشعارات',
    'settings.pushNotifications': 'الإشعارات الفورية',
    'settings.emailNotifications': 'إشعارات البريد الإلكتروني',
    'settings.smsNotifications': 'إشعارات الرسائل النصية',
    'settings.requestUpdates': 'تحديثات الطلبات',
    'settings.securityAlerts': 'تنبيهات الأمان',
    'settings.marketingEmails': 'رسائل التسويق الإلكترونية',
    'settings.appPreferences': 'تفضيلات التطبيق',
    'settings.darkMode': 'الوضع المظلم',
    'settings.support': 'الدعم',
    'settings.helpCenter': 'مركز المساعدة',
    'settings.privacyPolicy': 'سياسة الخصوصية',
    'settings.dangerZone': 'المنطقة الخطرة',
    'settings.deleteAccount': 'حذف الحساب',
    
    // Service Types
    'service.towing': 'خدمة السحب',
    'service.repair': 'خدمة الطريق',
    'service.mechanic': 'خدمة الميكانيكي',
    'service.tireRepair': 'إصلاح الإطارات المتنقل',
    'service.truckWash': 'غسيل الشاحنات المتنقل',
    'service.hoseRepair': 'إصلاح الخراطيم',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.messages': 'संदेश',
    'nav.leads': 'लीड्स',
    'nav.profile': 'प्रोफाइल',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.cancel': 'रद्द करें',
    'common.ok': 'ठीक है',
    'common.save': 'सेव करें',
    'common.delete': 'डिलीट करें',
    'common.edit': 'संपादित करें',
    'common.close': 'बंद करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.submit': 'जमा करें',
    'common.confirm': 'पुष्टि करें',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    
    // Home Screen
    'home.welcome': 'वापस स्वागत है,',
    'home.newRequest': 'नया अनुरोध',
    'home.getHelpNow': 'अभी मदद पाएं',
    'home.browseRequests': 'अनुरोध ब्राउज़ करें',
    'home.findNewJobs': 'नई नौकरियां खोजें',
    'home.availableRequests': 'उपलब्ध अनुरोध',
    'home.recentRequests': 'हाल के अनुरोध',
    'home.recentJobs': 'हाल की नौकरियां',
    'home.noRequestsYet': 'अभी तक कोई अनुरोध नहीं',
    'home.noJobsYet': 'अभी तक कोई नौकरी नहीं',
    'home.createFirstRequest': 'शुरू करने के लिए अपना पहला अनुरोध बनाएं',
    'home.browseAvailableRequests': 'शुरू करने के लिए उपलब्ध अनुरोधों को ब्राउज़ करें',
    'home.createRequest': 'अनुरोध बनाएं',
    'home.tapToView': 'विवरण देखने के लिए टैप करें',
    'home.referFriend': 'दोस्त को रेफर करें और $10 कमाएं',
    'home.shareRigSnap': 'RigSnap साझा करें और जब वे जुड़ें तो पुरस्कार पाएं',
    
    // Profile Screen
    'profile.title': 'प्रोफाइल',
    'profile.personalInformation': 'व्यक्तिगत जानकारी',
    'profile.name': 'नाम',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन',
    'profile.location': 'स्थान',
    'profile.memberSince': 'सदस्य बने',
    'profile.truckerInformation': 'ट्रक ड्राइवर जानकारी',
    'profile.truckType': 'ट्रक का प्रकार',
    'profile.licenseNumber': 'लाइसेंस नंबर',
    'profile.serviceProviderInformation': 'सेवा प्रदाता जानकारी',
    'profile.servicesOffered': 'प्रदान की जाने वाली सेवाएं',
    'profile.serviceRadius': 'सेवा त्रिज्या',
    'profile.certifications': 'प्रमाणन',
    'profile.paymentMethods': 'भुगतान के तरीके',
    'profile.settings': 'सेटिंग्स',
    'profile.accountSettings': 'खाता सेटिंग्स',
    'profile.languageRegion': 'भाषा और क्षेत्र',
    'profile.signOut': 'साइन आउट',
    'profile.rating': 'रेटिंग',
    'profile.notProvided': 'प्रदान नहीं किया गया',
    'profile.notSpecified': 'निर्दिष्ट नहीं',
    'profile.miles': 'मील',
    'profile.editProfile': 'प्रोफाइल संपादित करें',
    'profile.saveChanges': 'परिवर्तन सेव करें',
    'profile.cancel': 'रद्द करें',
    
    // Messages/Chat
    'chat.title': 'संदेश',
    'chat.messages': 'संदेश',
    'chat.noMessagesYet': 'अभी तक कोई संदेश नहीं',
    'chat.messagesWillAppear': 'जब आप सेवा प्रदाताओं के साथ चैट करना शुरू करेंगे तो संदेश यहां दिखाई देंगे',
    'chat.messagesWillAppearProvider': 'जब आप सेवा अनुरोध स्वीकार करेंगे तो संदेश यहां दिखाई देंगे',
    'chat.active': 'सक्रिय',
    'chat.completed': 'पूर्ण',
    'chat.typeMessage': 'संदेश टाइप करें...',
    'chat.trucker': 'ट्रक ड्राइवर',
    'chat.serviceProvider': 'सेवा प्रदाता',
    
    // Leads
    'leads.title': 'लीड ट्रैकिंग',
    'leads.leadTracking': 'लीड ट्रैकिंग',
    'leads.monitorLeadFees': 'अपनी लीड फीस और लेनदेन की निगरानी करें',
    'leads.netSpent': 'कुल खर्च',
    'leads.totalLeads': 'कुल लीड्स',
    'leads.refunded': 'वापस किया गया',
    'leads.penalties': 'जुर्माना',
    'leads.pending': 'लंबित',
    'leads.transactionHistory': 'लेनदेन इतिहास',
    'leads.noLeadFeesYet': 'अभी तक कोई लीड फीस नहीं',
    'leads.leadFeesWillAppear': 'जब सेवा प्रदाता आपके अनुरोध स्वीकार करेंगे तो लीड फीस यहां दिखाई देगी',
    'leads.leadFeesWillAppearProvider': 'जब आप सेवा अनुरोध स्वीकार करेंगे तो लीड फीस यहां दिखाई देगी',
    
    // Account Settings
    'settings.title': 'खाता सेटिंग्स',
    'settings.security': 'सुरक्षा',
    'settings.changePassword': 'पासवर्ड बदलें',
    'settings.updatePassword': 'अपने खाते का पासवर्ड अपडेट करें',
    'settings.languageRegion': 'भाषा और क्षेत्र',
    'settings.language': 'भाषा',
    'settings.currentLanguage': 'वर्तमान',
    'settings.notifications': 'सूचनाएं',
    'settings.pushNotifications': 'पुश सूचनाएं',
    'settings.emailNotifications': 'ईमेल सूचनाएं',
    'settings.smsNotifications': 'SMS सूचनाएं',
    'settings.requestUpdates': 'अनुरोध अपडेट',
    'settings.securityAlerts': 'सुरक्षा अलर्ट',
    'settings.marketingEmails': 'मार्केटिंग ईमेल',
    'settings.appPreferences': 'ऐप प्राथमिकताएं',
    'settings.darkMode': 'डार्क मोड',
    'settings.support': 'सहायता',
    'settings.helpCenter': 'सहायता केंद्र',
    'settings.privacyPolicy': 'गोपनीयता नीति',
    'settings.dangerZone': 'खतरनाक क्षेत्र',
    'settings.deleteAccount': 'खाता हटाएं',
    
    // Service Types
    'service.towing': 'टोइंग सेवा',
    'service.repair': 'रोड सेवा',
    'service.mechanic': 'मैकेनिक सेवा',
    'service.tireRepair': 'मोबाइल टायर रिपेयर',
    'service.truckWash': 'मोबाइल ट्रक वॉश',
    'service.hoseRepair': 'होज़ रिपेयर',
  },
  he: {
    // Navigation
    'nav.home': 'בית',
    'nav.messages': 'הודעות',
    'nav.leads': 'לידים',
    'nav.profile': 'פרופיל',
    
    // Common
    'common.loading': 'טוען...',
    'common.error': 'שגיאה',
    'common.success': 'הצלחה',
    'common.cancel': 'ביטול',
    'common.ok': 'אישור',
    'common.save': 'שמור',
    'common.delete': 'מחק',
    'common.edit': 'ערוך',
    'common.close': 'סגור',
    'common.back': 'חזור',
    'common.next': 'הבא',
    'common.previous': 'הקודם',
    'common.submit': 'שלח',
    'common.confirm': 'אשר',
    'common.yes': 'כן',
    'common.no': 'לא',
    
    // Home Screen
    'home.welcome': 'ברוך שובך,',
    'home.newRequest': 'בקשה חדשה',
    'home.getHelpNow': 'קבל עזרה עכשיו',
    'home.browseRequests': 'עיין בבקשות',
    'home.findNewJobs': 'מצא עבודות חדשות',
    'home.availableRequests': 'בקשות זמינות',
    'home.recentRequests': 'בקשות אחרונות',
    'home.recentJobs': 'עבודות אחרונות',
    'home.noRequestsYet': 'אין בקשות עדיין',
    'home.noJobsYet': 'אין עבודות עדיין',
    'home.createFirstRequest': 'צור את הבקשה הראשונה שלך כדי להתחיל',
    'home.browseAvailableRequests': 'עיין בבקשות זמינות כדי להתחיל',
    'home.createRequest': 'צור בקשה',
    'home.tapToView': 'הקש לצפייה בפרטים',
    'home.referFriend': 'הפנה חבר וזכה ב-$10',
    'home.shareRigSnap': 'שתף את RigSnap וקבל תגמולים כשהם מצטרפים',
    
    // Profile Screen
    'profile.title': 'פרופיל',
    'profile.personalInformation': 'מידע אישי',
    'profile.name': 'שם',
    'profile.email': 'אימייל',
    'profile.phone': 'טלפון',
    'profile.location': 'מיקום',
    'profile.memberSince': 'חבר מאז',
    'profile.truckerInformation': 'מידע נהג משאית',
    'profile.truckType': 'סוג משאית',
    'profile.licenseNumber': 'מספר רישיון',
    'profile.serviceProviderInformation': 'מידע ספק שירותים',
    'profile.servicesOffered': 'שירותים מוצעים',
    'profile.serviceRadius': 'רדיוס שירות',
    'profile.certifications': 'הסמכות',
    'profile.paymentMethods': 'אמצעי תשלום',
    'profile.settings': 'הגדרות',
    'profile.accountSettings': 'הגדרות חשבון',
    'profile.languageRegion': 'שפה ואזור',
    'profile.signOut': 'התנתק',
    'profile.rating': 'דירוג',
    'profile.notProvided': 'לא סופק',
    'profile.notSpecified': 'לא צוין',
    'profile.miles': 'מיילים',
    'profile.editProfile': 'ערוך פרופיל',
    'profile.saveChanges': 'שמור שינויים',
    'profile.cancel': 'ביטול',
    
    // Messages/Chat
    'chat.title': 'הודעות',
    'chat.messages': 'הודעות',
    'chat.noMessagesYet': 'אין הודעות עדיין',
    'chat.messagesWillAppear': 'הודעות יופיעו כאן כשתתחיל לשוחח עם ספקי שירותים',
    'chat.messagesWillAppearProvider': 'הודעות יופיעו כאן כשתקבל בקשות שירות',
    'chat.active': 'פעיל',
    'chat.completed': 'הושלם',
    'chat.typeMessage': 'הקלד הודעה...',
    'chat.trucker': 'נהג משאית',
    'chat.serviceProvider': 'ספק שירותים',
    
    // Leads
    'leads.title': 'מעקב לידים',
    'leads.leadTracking': 'מעקב לידים',
    'leads.monitorLeadFees': 'עקוב אחר עמלות הלידים והעסקאות שלך',
    'leads.netSpent': 'הוצאה נטו',
    'leads.totalLeads': 'סך הלידים',
    'leads.refunded': 'הוחזר',
    'leads.penalties': 'קנסות',
    'leads.pending': 'ממתין',
    'leads.transactionHistory': 'היסטוריית עסקאות',
    'leads.noLeadFeesYet': 'אין עמלות לידים עדיין',
    'leads.leadFeesWillAppear': 'עמלות לידים יופיעו כאן כשספקי שירותים יקבלו את הבקשות שלך',
    'leads.leadFeesWillAppearProvider': 'עמלות לידים יופיעו כאן כשתקבל בקשות שירות',
    
    // Account Settings
    'settings.title': 'הגדרות חשבון',
    'settings.security': 'אבטחה',
    'settings.changePassword': 'שנה סיסמה',
    'settings.updatePassword': 'עדכן את סיסמת החשבון שלך',
    'settings.languageRegion': 'שפה ואזור',
    'settings.language': 'שפה',
    'settings.currentLanguage': 'נוכחי',
    'settings.notifications': 'התראות',
    'settings.pushNotifications': 'התראות דחיפה',
    'settings.emailNotifications': 'התראות אימייל',
    'settings.smsNotifications': 'התראות SMS',
    'settings.requestUpdates': 'עדכוני בקשות',
    'settings.securityAlerts': 'התראות אבטחה',
    'settings.marketingEmails': 'אימיילי שיווק',
    'settings.appPreferences': 'העדפות אפליקציה',
    'settings.darkMode': 'מצב כהה',
    'settings.support': 'תמיכה',
    'settings.helpCenter': 'מרכז עזרה',
    'settings.privacyPolicy': 'מדיניות פרטיות',
    'settings.dangerZone': 'אזור מסוכן',
    'settings.deleteAccount': 'מחק חשבון',
    
    // Service Types
    'service.towing': 'שירות גרירה',
    'service.repair': 'שירות כביש',
    'service.mechanic': 'שירות מכונאי',
    'service.tireRepair': 'תיקון צמיגים נייד',
    'service.truckWash': 'שטיפת משאיות נייד',
    'service.hoseRepair': 'תיקון צינורות',
  },
  sv: {
    // Navigation
    'nav.home': 'Hem',
    'nav.messages': 'Meddelanden',
    'nav.leads': 'Leads',
    'nav.profile': 'Profil',
    
    // Common
    'common.loading': 'Laddar...',
    'common.error': 'Fel',
    'common.success': 'Framgång',
    'common.cancel': 'Avbryt',
    'common.ok': 'OK',
    'common.save': 'Spara',
    'common.delete': 'Ta bort',
    'common.edit': 'Redigera',
    'common.close': 'Stäng',
    'common.back': 'Tillbaka',
    'common.next': 'Nästa',
    'common.previous': 'Föregående',
    'common.submit': 'Skicka',
    'common.confirm': 'Bekräfta',
    'common.yes': 'Ja',
    'common.no': 'Nej',
    
    // Home Screen
    'home.welcome': 'Välkommen tillbaka,',
    'home.newRequest': 'Ny Förfrågan',
    'home.getHelpNow': 'Få hjälp nu',
    'home.browseRequests': 'Bläddra Förfrågningar',
    'home.findNewJobs': 'Hitta nya jobb',
    'home.availableRequests': 'Tillgängliga Förfrågningar',
    'home.recentRequests': 'Senaste Förfrågningar',
    'home.recentJobs': 'Senaste Jobb',
    'home.noRequestsYet': 'Inga förfrågningar än',
    'home.noJobsYet': 'Inga jobb än',
    'home.createFirstRequest': 'Skapa din första förfrågan för att komma igång',
    'home.browseAvailableRequests': 'Bläddra bland tillgängliga förfrågningar för att komma igång',
    'home.createRequest': 'Skapa Förfrågan',
    'home.tapToView': 'Tryck för att se detaljer',
    'home.referFriend': 'Hänvisa en Vän och Tjäna $10',
    'home.shareRigSnap': 'Dela RigSnap och få belöningar när de går med',
    
    // Profile Screen
    'profile.title': 'Profil',
    'profile.personalInformation': 'Personlig Information',
    'profile.name': 'Namn',
    'profile.email': 'E-post',
    'profile.phone': 'Telefon',
    'profile.location': 'Plats',
    'profile.memberSince': 'Medlem Sedan',
    'profile.truckerInformation': 'Lastbilschaufför Information',
    'profile.truckType': 'Lastbilstyp',
    'profile.licenseNumber': 'Licensnummer',
    'profile.serviceProviderInformation': 'Tjänsteleverantör Information',
    'profile.servicesOffered': 'Erbjudna Tjänster',
    'profile.serviceRadius': 'Tjänsteradie',
    'profile.certifications': 'Certifieringar',
    'profile.paymentMethods': 'Betalningsmetoder',
    'profile.settings': 'Inställningar',
    'profile.accountSettings': 'Kontoinställningar',
    'profile.languageRegion': 'Språk och Region',
    'profile.signOut': 'Logga Ut',
    'profile.rating': 'betyg',
    'profile.notProvided': 'Ej tillhandahållen',
    'profile.notSpecified': 'Ej specificerad',
    'profile.miles': 'mil',
    'profile.editProfile': 'Redigera Profil',
    'profile.saveChanges': 'Spara Ändringar',
    'profile.cancel': 'Avbryt',
    
    // Messages/Chat
    'chat.title': 'Meddelanden',
    'chat.messages': 'Meddelanden',
    'chat.noMessagesYet': 'Inga meddelanden än',
    'chat.messagesWillAppear': 'Meddelanden kommer att visas här när du börjar chatta med tjänsteleverantörer',
    'chat.messagesWillAppearProvider': 'Meddelanden kommer att visas här när du accepterar tjänsteförfrågningar',
    'chat.active': 'Aktiv',
    'chat.completed': 'Slutförd',
    'chat.typeMessage': 'Skriv ett meddelande...',
    'chat.trucker': 'Lastbilschaufför',
    'chat.serviceProvider': 'Tjänsteleverantör',
    
    // Leads
    'leads.title': 'Lead-spårning',
    'leads.leadTracking': 'Lead-spårning',
    'leads.monitorLeadFees': 'Övervaka dina lead-avgifter och transaktioner',
    'leads.netSpent': 'Netto Spenderat',
    'leads.totalLeads': 'Totala Leads',
    'leads.refunded': 'Återbetald',
    'leads.penalties': 'Straffavgifter',
    'leads.pending': 'Väntande',
    'leads.transactionHistory': 'Transaktionshistorik',
    'leads.noLeadFeesYet': 'Inga lead-avgifter än',
    'leads.leadFeesWillAppear': 'Lead-avgifter kommer att visas här när tjänsteleverantörer accepterar dina förfrågningar',
    'leads.leadFeesWillAppearProvider': 'Lead-avgifter kommer att visas här när du accepterar tjänsteförfrågningar',
    
    // Account Settings
    'settings.title': 'Kontoinställningar',
    'settings.security': 'Säkerhet',
    'settings.changePassword': 'Ändra Lösenord',
    'settings.updatePassword': 'Uppdatera ditt kontolösenord',
    'settings.languageRegion': 'Språk och Region',
    'settings.language': 'Språk',
    'settings.currentLanguage': 'Nuvarande',
    'settings.notifications': 'Notifieringar',
    'settings.pushNotifications': 'Push-notifieringar',
    'settings.emailNotifications': 'E-postnotifieringar',
    'settings.smsNotifications': 'SMS-notifieringar',
    'settings.requestUpdates': 'Förfrågningsuppdateringar',
    'settings.securityAlerts': 'Säkerhetsvarningar',
    'settings.marketingEmails': 'Marknadsförings-e-post',
    'settings.appPreferences': 'App-inställningar',
    'settings.darkMode': 'Mörkt Läge',
    'settings.support': 'Support',
    'settings.helpCenter': 'Hjälpcenter',
    'settings.privacyPolicy': 'Integritetspolicy',
    'settings.dangerZone': 'Farlig Zon',
    'settings.deleteAccount': 'Ta Bort Konto',
    
    // Service Types
    'service.towing': 'Bärgning',
    'service.repair': 'Vägservice',
    'service.mechanic': 'Mekanikertjänst',
    'service.tireRepair': 'Mobil Däckreparation',
    'service.truckWash': 'Mobil Lastbilstvätt',
    'service.hoseRepair': 'Slangreparation',
  },
  pl: {
    // Navigation
    'nav.home': 'Główna',
    'nav.messages': 'Wiadomości',
    'nav.leads': 'Leady',
    'nav.profile': 'Profil',
    
    // Common
    'common.loading': 'Ładowanie...',
    'common.error': 'Błąd',
    'common.success': 'Sukces',
    'common.cancel': 'Anuluj',
    'common.ok': 'OK',
    'common.save': 'Zapisz',
    'common.delete': 'Usuń',
    'common.edit': 'Edytuj',
    'common.close': 'Zamknij',
    'common.back': 'Wstecz',
    'common.next': 'Dalej',
    'common.previous': 'Poprzedni',
    'common.submit': 'Wyślij',
    'common.confirm': 'Potwierdź',
    'common.yes': 'Tak',
    'common.no': 'Nie',
    
    // Home Screen
    'home.welcome': 'Witaj ponownie,',
    'home.newRequest': 'Nowe Żądanie',
    'home.getHelpNow': 'Uzyskaj pomoc teraz',
    'home.browseRequests': 'Przeglądaj Żądania',
    'home.findNewJobs': 'Znajdź nowe prace',
    'home.availableRequests': 'Dostępne Żądania',
    'home.recentRequests': 'Ostatnie Żądania',
    'home.recentJobs': 'Ostatnie Prace',
    'home.noRequestsYet': 'Brak żądań jeszcze',
    'home.noJobsYet': 'Brak prac jeszcze',
    'home.createFirstRequest': 'Utwórz swoje pierwsze żądanie, aby rozpocząć',
    'home.browseAvailableRequests': 'Przeglądaj dostępne żądania, aby rozpocząć',
    'home.createRequest': 'Utwórz Żądanie',
    'home.tapToView': 'Dotknij, aby zobaczyć szczegóły',
    'home.referFriend': 'Poleć Przyjaciela i Zarabiaj $10',
    'home.shareRigSnap': 'Udostępnij RigSnap i otrzymuj nagrody, gdy dołączą',
    
    // Profile Screen
    'profile.title': 'Profil',
    'profile.personalInformation': 'Informacje Osobiste',
    'profile.name': 'Imię',
    'profile.email': 'E-mail',
    'profile.phone': 'Telefon',
    'profile.location': 'Lokalizacja',
    'profile.memberSince': 'Członek Od',
    'profile.truckerInformation': 'Informacje Kierowcy Ciężarówki',
    'profile.truckType': 'Typ Ciężarówki',
    'profile.licenseNumber': 'Numer Licencji',
    'profile.serviceProviderInformation': 'Informacje Dostawcy Usług',
    'profile.servicesOffered': 'Oferowane Usługi',
    'profile.serviceRadius': 'Zasięg Usług',
    'profile.certifications': 'Certyfikaty',
    'profile.paymentMethods': 'Metody Płatności',
    'profile.settings': 'Ustawienia',
    'profile.accountSettings': 'Ustawienia Konta',
    'profile.languageRegion': 'Język i Region',
    'profile.signOut': 'Wyloguj',
    'profile.rating': 'ocena',
    'profile.notProvided': 'Nie podano',
    'profile.notSpecified': 'Nie określono',
    'profile.miles': 'mile',
    'profile.editProfile': 'Edytuj Profil',
    'profile.saveChanges': 'Zapisz Zmiany',
    'profile.cancel': 'Anuluj',
    
    // Messages/Chat
    'chat.title': 'Wiadomości',
    'chat.messages': 'Wiadomości',
    'chat.noMessagesYet': 'Brak wiadomości jeszcze',
    'chat.messagesWillAppear': 'Wiadomości pojawią się tutaj, gdy zaczniesz rozmawiać z dostawcami usług',
    'chat.messagesWillAppearProvider': 'Wiadomości pojawią się tutaj, gdy zaakceptujesz żądania usług',
    'chat.active': 'Aktywny',
    'chat.completed': 'Ukończony',
    'chat.typeMessage': 'Wpisz wiadomość...',
    'chat.trucker': 'Kierowca Ciężarówki',
    'chat.serviceProvider': 'Dostawca Usług',
    
    // Leads
    'leads.title': 'Śledzenie Leadów',
    'leads.leadTracking': 'Śledzenie Leadów',
    'leads.monitorLeadFees': 'Monitoruj swoje opłaty za leady i transakcje',
    'leads.netSpent': 'Wydane Netto',
    'leads.totalLeads': 'Łączne Leady',
    'leads.refunded': 'Zwrócone',
    'leads.penalties': 'Kary',
    'leads.pending': 'Oczekujące',
    'leads.transactionHistory': 'Historia Transakcji',
    'leads.noLeadFeesYet': 'Brak opłat za leady jeszcze',
    'leads.leadFeesWillAppear': 'Opłaty za leady pojawią się tutaj, gdy dostawcy usług zaakceptują twoje żądania',
    'leads.leadFeesWillAppearProvider': 'Opłaty za leady pojawią się tutaj, gdy zaakceptujesz żądania usług',
    
    // Account Settings
    'settings.title': 'Ustawienia Konta',
    'settings.security': 'Bezpieczeństwo',
    'settings.changePassword': 'Zmień Hasło',
    'settings.updatePassword': 'Zaktualizuj hasło swojego konta',
    'settings.languageRegion': 'Język i Region',
    'settings.language': 'Język',
    'settings.currentLanguage': 'Obecny',
    'settings.notifications': 'Powiadomienia',
    'settings.pushNotifications': 'Powiadomienia Push',
    'settings.emailNotifications': 'Powiadomienia E-mail',
    'settings.smsNotifications': 'Powiadomienia SMS',
    'settings.requestUpdates': 'Aktualizacje Żądań',
    'settings.securityAlerts': 'Alerty Bezpieczeństwa',
    'settings.marketingEmails': 'E-maile Marketingowe',
    'settings.appPreferences': 'Preferencje Aplikacji',
    'settings.darkMode': 'Tryb Ciemny',
    'settings.support': 'Wsparcie',
    'settings.helpCenter': 'Centrum Pomocy',
    'settings.privacyPolicy': 'Polityka Prywatności',
    'settings.dangerZone': 'Strefa Niebezpieczna',
    'settings.deleteAccount': 'Usuń Konto',
    
    // Service Types
    'service.towing': 'Usługa Holowania',
    'service.repair': 'Usługa Drogowa',
    'service.mechanic': 'Usługa Mechaniczna',
    'service.tireRepair': 'Mobilna Naprawa Opon',
    'service.truckWash': 'Mobilne Mycie Ciężarówek',
    'service.hoseRepair': 'Naprawa Węży',
  },
};

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (languageCode: string) => void;
  t: (key: string, fallback?: string) => string;
  languages: Language[];
  getCurrentLanguage: () => Language;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const LANGUAGE_STORAGE_KEY = '@rigsnap_language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  useEffect(() => {
    loadLanguagePreference();
  }, []);

  const loadLanguagePreference = async () => {
    try {
      // Get from local storage
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage) {
        setCurrentLanguage(savedLanguage);
      }
    } catch (error) {
      console.error('Failed to load language preference:', error);
    }
  };

  const setLanguage = async (languageCode: string) => {
    try {
      setCurrentLanguage(languageCode);
      
      // Save to local storage
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, languageCode);
    } catch (error) {
      console.error('Failed to save language preference:', error);
    }
  };

  const t = (key: string, fallback?: string): string => {
    const translation = translations[currentLanguage]?.[key] || translations['en']?.[key] || fallback || key;
    return translation;
  };

  const getCurrentLanguage = (): Language => {
    return languages.find(lang => lang.code === currentLanguage) || languages[0];
  };

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      setLanguage,
      t,
      languages,
      getCurrentLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}